apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  labels:
    app: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      annotations:
        elastic.co/dataset: kubernetes.container_logs.checkout
        elastic.co/namespace: checkout
        elastic.co/preserve_original_event: "true"
      labels:
        app: checkout
    spec:
      containers:
        - name: checkout
          image: log-generator:v5
          imagePullPolicy: IfNotPresent
          stdin: true
          tty: true
